window.KB = [
{t:"identity",s:"Prakash Sharma is an AI/ML and Agentic AI developer working as AI & Data Engineer at Tradxlink since September 2025."},
{t:"identity",s:"Prakash is based in Pune, India and is open to remote, hybrid or onsite roles, especially in Pune."},
{t:"identity",s:"Prakash is looking for AI Engineer, GenAI Engineer, Applied AI Engineer, RAG/Agentic AI Developer, Python Developer and Data Engineer roles."},
{t:"education",s:"Prakash completed his BCA (Bachelor of Computer Applications) from Rungta College of Science and Technology, Chhattisgarh in 2023 with CGPA 8.0."},
{t:"education",s:"Prakash holds a Python certification from GUVI (Aug 2023) and a Data Science internship certificate from Internship Studio (Aug 2024 - Feb 2025)."},
{t:"skills",s:"Core skills: Python, FastAPI, REST APIs, Pydantic, AsyncIO, microservices, LLM APIs, prompt engineering, RAG, LlamaIndex, Milvus, MongoDB, GridFS."},
{t:"skills",s:"Agentic AI skills: multi-agent systems, LlamaIndex workflows, tool calling, query routing, traversal, agent-to-UI communication, preprocessing and postprocessing guards."},
{t:"skills",s:"Machine learning: scikit-learn, Pandas, NumPy, Random Forest, Prophet forecasting, feature engineering, data cleaning and A/B testing with z-tests."},
{t:"skills",s:"Document AI: Azure OCR, PyMuPDF4LLM and structured JSON extraction from invoices, bills of lading, purchase orders and other trade documents."},
{t:"skills",s:"Automation and scraping: Playwright, Selenium, Google Sheets API, web scraping and email automation."},
{t:"experience",s:"At Tradxlink, Prakash built a production multi-agent procurement system using LlamaIndex workflows with public, private and discovery sub-agents, API tool calling and response synthesis."},
{t:"experience",s:"He built enterprise RAG ingestion pipelines in Milvus with metadata filtering and public/private context isolation to reduce LLM hallucinations."},
{t:"experience",s:"He cut RAG response latency from 30+ seconds to under 10 seconds by replacing tree summarization with compact generation and optimizing API roundtrips, reducing token cost by about 50%."},
{t:"experience",s:"He hardened RAG retrieval security by enforcing user-context access controls before vector retrieval, preventing unauthorized cross-user data exposure in Milvus."},
{t:"experience",s:"He developed FastAPI microservices for voyage delay prediction, vessel reliability scoring and automated document feature extraction."},
{t:"experience",s:"He resolved large-document (300-page PDF) index failures by redesigning query-engine persistence around rebuildable GridFS references."},
{t:"experience",s:"He built document extraction pipelines combining PyMuPDF4LLM for text PDFs and Azure OCR for scanned documents to produce structured JSON from multi-page trade PDFs."},
{t:"experience",s:"He built crawlers for DGFT, RBI and CBIC government trade notifications and bridged them into the RAG platform through an advanced query API."},
{t:"experience",s:"At Augtech NextWealth (Jun-Sep 2025) Prakash annotated LiDAR data for autonomous-vehicle object detection, sustaining 95-97% quality against QA benchmarks."},
{t:"experience",s:"At Edxso (Apr-Jun 2025) he automated web data extraction with Python, Selenium and the Google Sheets API, cutting manual collection effort by about 80%."},
{t:"projects",s:"Mira is Prakash's live AI receptionist product for salons, barber shops and spas: conversational appointment booking, rescheduling, pricing and offers via Telegram, with WhatsApp planned. It is in beta with around 13 users and a public demo at mira.voxlabs.site."},
{t:"projects",s:"Redax is an in-progress AI redaction security auditor that scans redacted PDFs with OCR and LLMs to find residual PII or secret leaks and generates risk reports."},
{t:"projects",s:"TrimStack is an in-development AI auditor that connects to Gmail or Outlook, identifies unwanted subscriptions and produces cost-waste reports for SMBs."},
{t:"projects",s:"He built a credit-card fraud detection app with a Random Forest classifier in scikit-learn on imbalanced data, served through Streamlit."},
{t:"projects",s:"Other projects: multimodal emotion detector (Transformers, Whisper, DeepFace, OpenCV), desktop voice assistant, movie recommendation engine, Walmart sales forecasting with Prophet, and A/B testing analysis."},
{t:"contact",s:"You can contact Prakash by email at prakash.sharma.1462003@gmail.com or by phone at +91 8349353477."},
{t:"contact",s:"Prakash is on LinkedIn at linkedin.com/in/prakash-sharma-ps and on GitHub at github.com/l1ght14."},
{t:"narrative",s:"Career path: BCA in 2023, then data-science learning, an operations automation internship, an AI data internship on autonomous-vehicle LiDAR data, then AI & Data Engineer at Tradxlink building RAG and agentic systems, while independently shipping AI products."},
{t:"narrative",s:"Prakash's strongest areas are enterprise RAG, retrieval security, latency and cost optimization, document intelligence, agentic workflows and Python/FastAPI backend engineering."},
{t:"narrative",s:"His long-term goal is to build his own technology company; he already ships independent products like Mira."}
];
